baseURL = 'https://ok-komputer.github.io/'
languageCode = 'zh-CN'
title = 'ok-komputer'
theme = 'nostyleplease'
publishDir = 'docs'

[params]
    showtoc = true
    tocopen = true
    title = 'ok-komputer'
    description = "ok-komputer's blog"
    author = 'ok-komputer'
